version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Cambia a una contraseña segura
      MYSQL_DATABASE: crud_indicadores_equinorte
      MYSQL_USER: root
      MYSQL_PASSWORD: root  # Cambia a una contraseña segura
    ports:
      - "3307:3306"

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: crud-equinorte-prueba-myapp  # Asegúrate de que el nombre sea el mismo que tienes
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
